/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicioarcondicionado;

/**
 *
 * @author Nicholas
 */
public class TelaArCondicionado extends javax.swing.JFrame {

    /**
     * Creates new form TelaArCondicionado
     */
    public TelaArCondicionado() {
        initComponents();
    }
    private int nValorPadraoBTU = 600;
    private int nQuantidadePessoasAmbiente;
    private int nQuantidadeAparelhos;
    private int nTamanhoAmbiente;
    private int nValorTotalBtus;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        incidenciaSolarCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        quantidadeAparelhosTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tamanhoAmbienteTextField = new javax.swing.JTextField();
        valorTotalBtuLabel = new javax.swing.JLabel();
        calculaBtuButton = new javax.swing.JButton();
        quantidadePessoasAmbienteTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cálculo de BTUS necessários para um ambiente");

        jLabel2.setText("Sugestão de BTU'S:");

        incidenciaSolarCheckBox.setText("Ambiente possui incidência solar extra");
        incidenciaSolarCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incidenciaSolarCheckBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade total de pessoas no ambiente:");

        jLabel4.setText("Quantidade de aparelhos que geram calor no ambiente:");

        quantidadeAparelhosTextField.setColumns(6);
        quantidadeAparelhosTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantidadeAparelhosTextField.setText("valor");
        quantidadeAparelhosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeAparelhosTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Tamanho em m² do ambiente");

        tamanhoAmbienteTextField.setColumns(6);
        tamanhoAmbienteTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tamanhoAmbienteTextField.setText("valor");
        tamanhoAmbienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanhoAmbienteTextFieldActionPerformed(evt);
            }
        });

        valorTotalBtuLabel.setBackground(new java.awt.Color(255, 255, 255));
        valorTotalBtuLabel.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        valorTotalBtuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorTotalBtuLabel.setText("Valor recomendado de Btus");
        valorTotalBtuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        calculaBtuButton.setText("Calcular BTUS sugeridos");
        calculaBtuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaBtuButtonActionPerformed(evt);
            }
        });

        quantidadePessoasAmbienteTextField.setColumns(6);
        quantidadePessoasAmbienteTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantidadePessoasAmbienteTextField.setText("valor");
        quantidadePessoasAmbienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadePessoasAmbienteTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(incidenciaSolarCheckBox)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(quantidadePessoasAmbienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(quantidadeAparelhosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tamanhoAmbienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(calculaBtuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(valorTotalBtuLabel))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(incidenciaSolarCheckBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantidadePessoasAmbienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(quantidadeAparelhosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tamanhoAmbienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(calculaBtuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valorTotalBtuLabel)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incidenciaSolarCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incidenciaSolarCheckBoxActionPerformed
        if(incidenciaSolarCheckBox.isSelected())
        {
            setnValorPadraoBTU(800);
        }
        else
        {
            setnValorPadraoBTU(600);
        }
    }//GEN-LAST:event_incidenciaSolarCheckBoxActionPerformed

    private void quantidadeAparelhosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeAparelhosTextFieldActionPerformed
         
    }//GEN-LAST:event_quantidadeAparelhosTextFieldActionPerformed

    private void tamanhoAmbienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanhoAmbienteTextFieldActionPerformed
         
    }//GEN-LAST:event_tamanhoAmbienteTextFieldActionPerformed

    private void calculaBtuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculaBtuButtonActionPerformed
        setnQuantidadePessoasAmbiente(Integer.parseInt(quantidadePessoasAmbienteTextField.getText()) -1);
        setnQuantidadeAparelhos(Integer.parseInt(quantidadeAparelhosTextField.getText()));
        setnTamanhoAmbiente(Integer.parseInt(tamanhoAmbienteTextField.getText()));
        setnValorTotalBtus( getnValorPadraoBTU() * getnQuantidadeAparelhos()  +  getnValorPadraoBTU() * getnQuantidadePessoasAmbiente()  +  getnValorPadraoBTU() *  getnTamanhoAmbiente() );
        valorTotalBtuLabel.setText(getnValorTotalBtus() + " BTUS");
    }//GEN-LAST:event_calculaBtuButtonActionPerformed

    private void quantidadePessoasAmbienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadePessoasAmbienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadePessoasAmbienteTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaArCondicionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaArCondicionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaArCondicionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaArCondicionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaArCondicionado().setVisible(true);
            }
        });
    }

    public int getnValorPadraoBTU() {
        return nValorPadraoBTU;
    }

    public void setnValorPadraoBTU(int nValorPadraoBTU) {
        this.nValorPadraoBTU = nValorPadraoBTU;
    }

    public int getnQuantidadePessoasAmbiente() {
        return nQuantidadePessoasAmbiente;
    }

    public void setnQuantidadePessoasAmbiente(int nQuantidadePessoasAmbiente) {
        this.nQuantidadePessoasAmbiente = nQuantidadePessoasAmbiente;
    }

    public int getnQuantidadeAparelhos() {
        return nQuantidadeAparelhos;
    }

    public void setnQuantidadeAparelhos(int nQuantidadeAparelhos) {
        this.nQuantidadeAparelhos = nQuantidadeAparelhos;
    }

    public int getnTamanhoAmbiente() {
        return nTamanhoAmbiente;
    }

    public void setnTamanhoAmbiente(int nTamanhoAmbiente) {
        this.nTamanhoAmbiente = nTamanhoAmbiente;
    }

    public int getnValorTotalBtus() {
        return nValorTotalBtus;
    }

    public void setnValorTotalBtus(int nValorTotalBtus) {
        this.nValorTotalBtus = nValorTotalBtus;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculaBtuButton;
    private javax.swing.JCheckBox incidenciaSolarCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField quantidadeAparelhosTextField;
    private javax.swing.JTextField quantidadePessoasAmbienteTextField;
    private javax.swing.JTextField tamanhoAmbienteTextField;
    private javax.swing.JLabel valorTotalBtuLabel;
    // End of variables declaration//GEN-END:variables
}
